algoritmo "exercicio12"

var
nome1, nome2: caractere
idade1, idade2: inteiro
inicio
escreva("Primeira pessoa: ")
leia(nome1)
escreva("Idade dele(a): ")
leia(idade1)
escreva("Segunda pessoa: ")
leia(nome2)
escreva("Idade dele(a): ")
leia(idade2)

se idade1 > idade2 entao
escreval("A pessoa mais velha é o(a) ", nome1)
senao
se idade2 > idade1 entao
escreva("A pessoa mais velha é o(a) ", nome2)
senao
escreva("Ambas idades sao iguais")
fimse
fimse
fimalgoritmo
