algoritmo "exercicio_09"

var
idade: inteiro
inicio
escreva("Digite sua idade: ")
leia(idade)

se idade <= 2 entao
escreva("Voce é um bebe")
senao
se idade <= 12 entao
escreva("Voce é uma criança")
senao
se idade <= 17 entao
escreva("Voce é um adolescente")
senao
se idade <= 64 entao
escreva("Voce é um adulto")
senao
se idade >= 65 entao
escreva("Voce é um idoso")
fimse
fimse
fimse
fimse
fimse
fimalgoritmo
